theme: jekyll-theme-minimal
title: Harsh Dolhare
description: Hi! I am a second year electrical undergraduate at IIT, Bombay.
             Professional Binge-watcher , Travel junkie , Food lover , History Buff and mosquito slayer in spare time.
